/*
Flowpipe

Testing ModApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package flowpipeapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/turbot/flowpipe-sdk-go"
)

func Test_flowpipeapi_ModApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ModApiService Get", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var modName string

		resp, httpRes, err := apiClient.ModApi.Get(context.Background(), modName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
