/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the ListIntegrationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIntegrationResponse{}

// ListIntegrationResponse struct for ListIntegrationResponse
type ListIntegrationResponse struct {
	Items []FpIntegration `json:"items,omitempty"`
	NextToken *string `json:"next_token,omitempty"`
}
func (o ListIntegrationResponse) GetResourceType() string {
	return "ListIntegrationResponse"
}
// NewListIntegrationResponse instantiates a new ListIntegrationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIntegrationResponse() *ListIntegrationResponse {
	this := ListIntegrationResponse{}
	return &this
}

// NewListIntegrationResponseWithDefaults instantiates a new ListIntegrationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIntegrationResponseWithDefaults() *ListIntegrationResponse {
	this := ListIntegrationResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListIntegrationResponse) GetItems() []FpIntegration {
	if o == nil || IsNil(o.Items) {
		var ret []FpIntegration
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIntegrationResponse) GetItemsOk() ([]FpIntegration, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListIntegrationResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []FpIntegration and assigns it to the Items field.
func (o *ListIntegrationResponse) SetItems(v []FpIntegration) {
	o.Items = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListIntegrationResponse) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIntegrationResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListIntegrationResponse) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListIntegrationResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListIntegrationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIntegrationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextToken) {
		toSerialize["next_token"] = o.NextToken
	}
	return toSerialize, nil
}

type NullableListIntegrationResponse struct {
	value *ListIntegrationResponse
	isSet bool
}

func (v NullableListIntegrationResponse) Get() *ListIntegrationResponse {
	return v.value
}

func (v *NullableListIntegrationResponse) Set(val *ListIntegrationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListIntegrationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListIntegrationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIntegrationResponse(val *ListIntegrationResponse) *NullableListIntegrationResponse {
	return &NullableListIntegrationResponse{value: val, isSet: true}
}

func (v NullableListIntegrationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIntegrationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


