/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the PerrErrorDetailModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerrErrorDetailModel{}

// PerrErrorDetailModel struct for PerrErrorDetailModel
type PerrErrorDetailModel struct {
	Location *string `json:"location,omitempty"`
	Message *string `json:"message,omitempty"`
}
func (o PerrErrorDetailModel) GetResourceType() string {
	return "PerrErrorDetailModel"
}
// NewPerrErrorDetailModel instantiates a new PerrErrorDetailModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerrErrorDetailModel() *PerrErrorDetailModel {
	this := PerrErrorDetailModel{}
	return &this
}

// NewPerrErrorDetailModelWithDefaults instantiates a new PerrErrorDetailModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerrErrorDetailModelWithDefaults() *PerrErrorDetailModel {
	this := PerrErrorDetailModel{}
	return &this
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *PerrErrorDetailModel) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerrErrorDetailModel) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *PerrErrorDetailModel) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *PerrErrorDetailModel) SetLocation(v string) {
	o.Location = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PerrErrorDetailModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PerrErrorDetailModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PerrErrorDetailModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PerrErrorDetailModel) SetMessage(v string) {
	o.Message = &v
}

func (o PerrErrorDetailModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PerrErrorDetailModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePerrErrorDetailModel struct {
	value *PerrErrorDetailModel
	isSet bool
}

func (v NullablePerrErrorDetailModel) Get() *PerrErrorDetailModel {
	return v.value
}

func (v *NullablePerrErrorDetailModel) Set(val *PerrErrorDetailModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePerrErrorDetailModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePerrErrorDetailModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerrErrorDetailModel(val *PerrErrorDetailModel) *NullablePerrErrorDetailModel {
	return &NullablePerrErrorDetailModel{value: val, isSet: true}
}

func (v NullablePerrErrorDetailModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerrErrorDetailModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


