/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the ModconfigPipelineOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModconfigPipelineOutput{}

// ModconfigPipelineOutput struct for ModconfigPipelineOutput
type ModconfigPipelineOutput struct {
	DependsOn []string `json:"depends_on,omitempty"`
	Name *string `json:"name,omitempty"`
	Resolved *bool `json:"resolved,omitempty"`
	Sensitive *bool `json:"sensitive,omitempty"`
	Value map[string]interface{} `json:"value,omitempty"`
}
func (o ModconfigPipelineOutput) GetResourceType() string {
	return "ModconfigPipelineOutput"
}
// NewModconfigPipelineOutput instantiates a new ModconfigPipelineOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModconfigPipelineOutput() *ModconfigPipelineOutput {
	this := ModconfigPipelineOutput{}
	return &this
}

// NewModconfigPipelineOutputWithDefaults instantiates a new ModconfigPipelineOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModconfigPipelineOutputWithDefaults() *ModconfigPipelineOutput {
	this := ModconfigPipelineOutput{}
	return &this
}

// GetDependsOn returns the DependsOn field value if set, zero value otherwise.
func (o *ModconfigPipelineOutput) GetDependsOn() []string {
	if o == nil || IsNil(o.DependsOn) {
		var ret []string
		return ret
	}
	return o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigPipelineOutput) GetDependsOnOk() ([]string, bool) {
	if o == nil || IsNil(o.DependsOn) {
		return nil, false
	}
	return o.DependsOn, true
}

// HasDependsOn returns a boolean if a field has been set.
func (o *ModconfigPipelineOutput) HasDependsOn() bool {
	if o != nil && !IsNil(o.DependsOn) {
		return true
	}

	return false
}

// SetDependsOn gets a reference to the given []string and assigns it to the DependsOn field.
func (o *ModconfigPipelineOutput) SetDependsOn(v []string) {
	o.DependsOn = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ModconfigPipelineOutput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigPipelineOutput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ModconfigPipelineOutput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ModconfigPipelineOutput) SetName(v string) {
	o.Name = &v
}

// GetResolved returns the Resolved field value if set, zero value otherwise.
func (o *ModconfigPipelineOutput) GetResolved() bool {
	if o == nil || IsNil(o.Resolved) {
		var ret bool
		return ret
	}
	return *o.Resolved
}

// GetResolvedOk returns a tuple with the Resolved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigPipelineOutput) GetResolvedOk() (*bool, bool) {
	if o == nil || IsNil(o.Resolved) {
		return nil, false
	}
	return o.Resolved, true
}

// HasResolved returns a boolean if a field has been set.
func (o *ModconfigPipelineOutput) HasResolved() bool {
	if o != nil && !IsNil(o.Resolved) {
		return true
	}

	return false
}

// SetResolved gets a reference to the given bool and assigns it to the Resolved field.
func (o *ModconfigPipelineOutput) SetResolved(v bool) {
	o.Resolved = &v
}

// GetSensitive returns the Sensitive field value if set, zero value otherwise.
func (o *ModconfigPipelineOutput) GetSensitive() bool {
	if o == nil || IsNil(o.Sensitive) {
		var ret bool
		return ret
	}
	return *o.Sensitive
}

// GetSensitiveOk returns a tuple with the Sensitive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigPipelineOutput) GetSensitiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Sensitive) {
		return nil, false
	}
	return o.Sensitive, true
}

// HasSensitive returns a boolean if a field has been set.
func (o *ModconfigPipelineOutput) HasSensitive() bool {
	if o != nil && !IsNil(o.Sensitive) {
		return true
	}

	return false
}

// SetSensitive gets a reference to the given bool and assigns it to the Sensitive field.
func (o *ModconfigPipelineOutput) SetSensitive(v bool) {
	o.Sensitive = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ModconfigPipelineOutput) GetValue() map[string]interface{} {
	if o == nil || IsNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigPipelineOutput) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ModconfigPipelineOutput) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *ModconfigPipelineOutput) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o ModconfigPipelineOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModconfigPipelineOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DependsOn) {
		toSerialize["depends_on"] = o.DependsOn
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Resolved) {
		toSerialize["resolved"] = o.Resolved
	}
	if !IsNil(o.Sensitive) {
		toSerialize["sensitive"] = o.Sensitive
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableModconfigPipelineOutput struct {
	value *ModconfigPipelineOutput
	isSet bool
}

func (v NullableModconfigPipelineOutput) Get() *ModconfigPipelineOutput {
	return v.value
}

func (v *NullableModconfigPipelineOutput) Set(val *ModconfigPipelineOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableModconfigPipelineOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableModconfigPipelineOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModconfigPipelineOutput(val *ModconfigPipelineOutput) *NullableModconfigPipelineOutput {
	return &NullableModconfigPipelineOutput{value: val, isSet: true}
}

func (v NullableModconfigPipelineOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModconfigPipelineOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


