/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the ExecutionSnapshotPanelData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExecutionSnapshotPanelData{}

// ExecutionSnapshotPanelData struct for ExecutionSnapshotPanelData
type ExecutionSnapshotPanelData struct {
	Columns []ExecutionSnapshotPanelDataColumn `json:"columns,omitempty"`
	Rows []map[string]interface{} `json:"rows,omitempty"`
}
func (o ExecutionSnapshotPanelData) GetResourceType() string {
	return "ExecutionSnapshotPanelData"
}
// NewExecutionSnapshotPanelData instantiates a new ExecutionSnapshotPanelData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecutionSnapshotPanelData() *ExecutionSnapshotPanelData {
	this := ExecutionSnapshotPanelData{}
	return &this
}

// NewExecutionSnapshotPanelDataWithDefaults instantiates a new ExecutionSnapshotPanelData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecutionSnapshotPanelDataWithDefaults() *ExecutionSnapshotPanelData {
	this := ExecutionSnapshotPanelData{}
	return &this
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *ExecutionSnapshotPanelData) GetColumns() []ExecutionSnapshotPanelDataColumn {
	if o == nil || IsNil(o.Columns) {
		var ret []ExecutionSnapshotPanelDataColumn
		return ret
	}
	return o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutionSnapshotPanelData) GetColumnsOk() ([]ExecutionSnapshotPanelDataColumn, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *ExecutionSnapshotPanelData) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given []ExecutionSnapshotPanelDataColumn and assigns it to the Columns field.
func (o *ExecutionSnapshotPanelData) SetColumns(v []ExecutionSnapshotPanelDataColumn) {
	o.Columns = v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *ExecutionSnapshotPanelData) GetRows() []map[string]interface{} {
	if o == nil || IsNil(o.Rows) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecutionSnapshotPanelData) GetRowsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *ExecutionSnapshotPanelData) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []map[string]interface{} and assigns it to the Rows field.
func (o *ExecutionSnapshotPanelData) SetRows(v []map[string]interface{}) {
	o.Rows = v
}

func (o ExecutionSnapshotPanelData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExecutionSnapshotPanelData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	return toSerialize, nil
}

type NullableExecutionSnapshotPanelData struct {
	value *ExecutionSnapshotPanelData
	isSet bool
}

func (v NullableExecutionSnapshotPanelData) Get() *ExecutionSnapshotPanelData {
	return v.value
}

func (v *NullableExecutionSnapshotPanelData) Set(val *ExecutionSnapshotPanelData) {
	v.value = val
	v.isSet = true
}

func (v NullableExecutionSnapshotPanelData) IsSet() bool {
	return v.isSet
}

func (v *NullableExecutionSnapshotPanelData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecutionSnapshotPanelData(val *ExecutionSnapshotPanelData) *NullableExecutionSnapshotPanelData {
	return &NullableExecutionSnapshotPanelData{value: val, isSet: true}
}

func (v NullableExecutionSnapshotPanelData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecutionSnapshotPanelData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


