/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the PcerrErrorModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PcerrErrorModel{}

// PcerrErrorModel struct for PcerrErrorModel
type PcerrErrorModel struct {
	Detail *string `json:"detail,omitempty"`
	Instance string `json:"instance"`
	// All errors are fatal unless specified
	Retryable *bool `json:"retryable,omitempty"`
	Status int32 `json:"status"`
	Title string `json:"title"`
	Type string `json:"type"`
	ValidationErrors []PcerrErrorDetailModel `json:"validation_errors,omitempty"`
}
func (o PcerrErrorModel) GetResourceType() string {
	return "PcerrErrorModel"
}
// NewPcerrErrorModel instantiates a new PcerrErrorModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPcerrErrorModel(instance string, status int32, title string, type_ string) *PcerrErrorModel {
	this := PcerrErrorModel{}
	this.Instance = instance
	this.Status = status
	this.Title = title
	this.Type = type_
	return &this
}

// NewPcerrErrorModelWithDefaults instantiates a new PcerrErrorModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPcerrErrorModelWithDefaults() *PcerrErrorModel {
	this := PcerrErrorModel{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *PcerrErrorModel) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *PcerrErrorModel) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *PcerrErrorModel) SetDetail(v string) {
	o.Detail = &v
}

// GetInstance returns the Instance field value
func (o *PcerrErrorModel) GetInstance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetInstanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instance, true
}

// SetInstance sets field value
func (o *PcerrErrorModel) SetInstance(v string) {
	o.Instance = v
}

// GetRetryable returns the Retryable field value if set, zero value otherwise.
func (o *PcerrErrorModel) GetRetryable() bool {
	if o == nil || IsNil(o.Retryable) {
		var ret bool
		return ret
	}
	return *o.Retryable
}

// GetRetryableOk returns a tuple with the Retryable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetRetryableOk() (*bool, bool) {
	if o == nil || IsNil(o.Retryable) {
		return nil, false
	}
	return o.Retryable, true
}

// HasRetryable returns a boolean if a field has been set.
func (o *PcerrErrorModel) HasRetryable() bool {
	if o != nil && !IsNil(o.Retryable) {
		return true
	}

	return false
}

// SetRetryable gets a reference to the given bool and assigns it to the Retryable field.
func (o *PcerrErrorModel) SetRetryable(v bool) {
	o.Retryable = &v
}

// GetStatus returns the Status field value
func (o *PcerrErrorModel) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PcerrErrorModel) SetStatus(v int32) {
	o.Status = v
}

// GetTitle returns the Title field value
func (o *PcerrErrorModel) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PcerrErrorModel) SetTitle(v string) {
	o.Title = v
}

// GetType returns the Type field value
func (o *PcerrErrorModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PcerrErrorModel) SetType(v string) {
	o.Type = v
}

// GetValidationErrors returns the ValidationErrors field value if set, zero value otherwise.
func (o *PcerrErrorModel) GetValidationErrors() []PcerrErrorDetailModel {
	if o == nil || IsNil(o.ValidationErrors) {
		var ret []PcerrErrorDetailModel
		return ret
	}
	return o.ValidationErrors
}

// GetValidationErrorsOk returns a tuple with the ValidationErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PcerrErrorModel) GetValidationErrorsOk() ([]PcerrErrorDetailModel, bool) {
	if o == nil || IsNil(o.ValidationErrors) {
		return nil, false
	}
	return o.ValidationErrors, true
}

// HasValidationErrors returns a boolean if a field has been set.
func (o *PcerrErrorModel) HasValidationErrors() bool {
	if o != nil && !IsNil(o.ValidationErrors) {
		return true
	}

	return false
}

// SetValidationErrors gets a reference to the given []PcerrErrorDetailModel and assigns it to the ValidationErrors field.
func (o *PcerrErrorModel) SetValidationErrors(v []PcerrErrorDetailModel) {
	o.ValidationErrors = v
}

func (o PcerrErrorModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PcerrErrorModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	toSerialize["instance"] = o.Instance
	if !IsNil(o.Retryable) {
		toSerialize["retryable"] = o.Retryable
	}
	toSerialize["status"] = o.Status
	toSerialize["title"] = o.Title
	toSerialize["type"] = o.Type
	if !IsNil(o.ValidationErrors) {
		toSerialize["validation_errors"] = o.ValidationErrors
	}
	return toSerialize, nil
}

type NullablePcerrErrorModel struct {
	value *PcerrErrorModel
	isSet bool
}

func (v NullablePcerrErrorModel) Get() *PcerrErrorModel {
	return v.value
}

func (v *NullablePcerrErrorModel) Set(val *PcerrErrorModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePcerrErrorModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePcerrErrorModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePcerrErrorModel(val *PcerrErrorModel) *NullablePcerrErrorModel {
	return &NullablePcerrErrorModel{value: val, isSet: true}
}

func (v NullablePcerrErrorModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePcerrErrorModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


