/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the ModconfigStepLoop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModconfigStepLoop{}

// ModconfigStepLoop struct for ModconfigStepLoop
type ModconfigStepLoop struct {
	Index int32 `json:"index"`
	Input map[string]interface{} `json:"input,omitempty"`
	LoopCompleted *bool `json:"loop_completed,omitempty"`
}
func (o ModconfigStepLoop) GetResourceType() string {
	return "ModconfigStepLoop"
}
// NewModconfigStepLoop instantiates a new ModconfigStepLoop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModconfigStepLoop(index int32) *ModconfigStepLoop {
	this := ModconfigStepLoop{}
	this.Index = index
	return &this
}

// NewModconfigStepLoopWithDefaults instantiates a new ModconfigStepLoop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModconfigStepLoopWithDefaults() *ModconfigStepLoop {
	this := ModconfigStepLoop{}
	return &this
}

// GetIndex returns the Index field value
func (o *ModconfigStepLoop) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *ModconfigStepLoop) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *ModconfigStepLoop) SetIndex(v int32) {
	o.Index = v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *ModconfigStepLoop) GetInput() map[string]interface{} {
	if o == nil || IsNil(o.Input) {
		var ret map[string]interface{}
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigStepLoop) GetInputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Input) {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *ModconfigStepLoop) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given map[string]interface{} and assigns it to the Input field.
func (o *ModconfigStepLoop) SetInput(v map[string]interface{}) {
	o.Input = v
}

// GetLoopCompleted returns the LoopCompleted field value if set, zero value otherwise.
func (o *ModconfigStepLoop) GetLoopCompleted() bool {
	if o == nil || IsNil(o.LoopCompleted) {
		var ret bool
		return ret
	}
	return *o.LoopCompleted
}

// GetLoopCompletedOk returns a tuple with the LoopCompleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModconfigStepLoop) GetLoopCompletedOk() (*bool, bool) {
	if o == nil || IsNil(o.LoopCompleted) {
		return nil, false
	}
	return o.LoopCompleted, true
}

// HasLoopCompleted returns a boolean if a field has been set.
func (o *ModconfigStepLoop) HasLoopCompleted() bool {
	if o != nil && !IsNil(o.LoopCompleted) {
		return true
	}

	return false
}

// SetLoopCompleted gets a reference to the given bool and assigns it to the LoopCompleted field.
func (o *ModconfigStepLoop) SetLoopCompleted(v bool) {
	o.LoopCompleted = &v
}

func (o ModconfigStepLoop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModconfigStepLoop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.LoopCompleted) {
		toSerialize["loop_completed"] = o.LoopCompleted
	}
	return toSerialize, nil
}

type NullableModconfigStepLoop struct {
	value *ModconfigStepLoop
	isSet bool
}

func (v NullableModconfigStepLoop) Get() *ModconfigStepLoop {
	return v.value
}

func (v *NullableModconfigStepLoop) Set(val *ModconfigStepLoop) {
	v.value = val
	v.isSet = true
}

func (v NullableModconfigStepLoop) IsSet() bool {
	return v.isSet
}

func (v *NullableModconfigStepLoop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModconfigStepLoop(val *ModconfigStepLoop) *NullableModconfigStepLoop {
	return &NullableModconfigStepLoop{value: val, isSet: true}
}

func (v NullableModconfigStepLoop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModconfigStepLoop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


