/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the FlowpipeTriggerResponseMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlowpipeTriggerResponseMetadata{}

// FlowpipeTriggerResponseMetadata struct for FlowpipeTriggerResponseMetadata
type FlowpipeTriggerResponseMetadata struct {
	IsStale *bool `json:"is_stale,omitempty"`
	LastLoaded *string `json:"last_loaded,omitempty"`
	Name *string `json:"name,omitempty"`
	ProcessId *string `json:"process_id,omitempty"`
	Type *string `json:"type,omitempty"`
}
func (o FlowpipeTriggerResponseMetadata) GetResourceType() string {
	return "FlowpipeTriggerResponseMetadata"
}
// NewFlowpipeTriggerResponseMetadata instantiates a new FlowpipeTriggerResponseMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlowpipeTriggerResponseMetadata() *FlowpipeTriggerResponseMetadata {
	this := FlowpipeTriggerResponseMetadata{}
	return &this
}

// NewFlowpipeTriggerResponseMetadataWithDefaults instantiates a new FlowpipeTriggerResponseMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlowpipeTriggerResponseMetadataWithDefaults() *FlowpipeTriggerResponseMetadata {
	this := FlowpipeTriggerResponseMetadata{}
	return &this
}

// GetIsStale returns the IsStale field value if set, zero value otherwise.
func (o *FlowpipeTriggerResponseMetadata) GetIsStale() bool {
	if o == nil || IsNil(o.IsStale) {
		var ret bool
		return ret
	}
	return *o.IsStale
}

// GetIsStaleOk returns a tuple with the IsStale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlowpipeTriggerResponseMetadata) GetIsStaleOk() (*bool, bool) {
	if o == nil || IsNil(o.IsStale) {
		return nil, false
	}
	return o.IsStale, true
}

// HasIsStale returns a boolean if a field has been set.
func (o *FlowpipeTriggerResponseMetadata) HasIsStale() bool {
	if o != nil && !IsNil(o.IsStale) {
		return true
	}

	return false
}

// SetIsStale gets a reference to the given bool and assigns it to the IsStale field.
func (o *FlowpipeTriggerResponseMetadata) SetIsStale(v bool) {
	o.IsStale = &v
}

// GetLastLoaded returns the LastLoaded field value if set, zero value otherwise.
func (o *FlowpipeTriggerResponseMetadata) GetLastLoaded() string {
	if o == nil || IsNil(o.LastLoaded) {
		var ret string
		return ret
	}
	return *o.LastLoaded
}

// GetLastLoadedOk returns a tuple with the LastLoaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlowpipeTriggerResponseMetadata) GetLastLoadedOk() (*string, bool) {
	if o == nil || IsNil(o.LastLoaded) {
		return nil, false
	}
	return o.LastLoaded, true
}

// HasLastLoaded returns a boolean if a field has been set.
func (o *FlowpipeTriggerResponseMetadata) HasLastLoaded() bool {
	if o != nil && !IsNil(o.LastLoaded) {
		return true
	}

	return false
}

// SetLastLoaded gets a reference to the given string and assigns it to the LastLoaded field.
func (o *FlowpipeTriggerResponseMetadata) SetLastLoaded(v string) {
	o.LastLoaded = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FlowpipeTriggerResponseMetadata) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlowpipeTriggerResponseMetadata) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FlowpipeTriggerResponseMetadata) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FlowpipeTriggerResponseMetadata) SetName(v string) {
	o.Name = &v
}

// GetProcessId returns the ProcessId field value if set, zero value otherwise.
func (o *FlowpipeTriggerResponseMetadata) GetProcessId() string {
	if o == nil || IsNil(o.ProcessId) {
		var ret string
		return ret
	}
	return *o.ProcessId
}

// GetProcessIdOk returns a tuple with the ProcessId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlowpipeTriggerResponseMetadata) GetProcessIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProcessId) {
		return nil, false
	}
	return o.ProcessId, true
}

// HasProcessId returns a boolean if a field has been set.
func (o *FlowpipeTriggerResponseMetadata) HasProcessId() bool {
	if o != nil && !IsNil(o.ProcessId) {
		return true
	}

	return false
}

// SetProcessId gets a reference to the given string and assigns it to the ProcessId field.
func (o *FlowpipeTriggerResponseMetadata) SetProcessId(v string) {
	o.ProcessId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FlowpipeTriggerResponseMetadata) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlowpipeTriggerResponseMetadata) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FlowpipeTriggerResponseMetadata) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FlowpipeTriggerResponseMetadata) SetType(v string) {
	o.Type = &v
}

func (o FlowpipeTriggerResponseMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlowpipeTriggerResponseMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsStale) {
		toSerialize["is_stale"] = o.IsStale
	}
	if !IsNil(o.LastLoaded) {
		toSerialize["last_loaded"] = o.LastLoaded
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ProcessId) {
		toSerialize["process_id"] = o.ProcessId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableFlowpipeTriggerResponseMetadata struct {
	value *FlowpipeTriggerResponseMetadata
	isSet bool
}

func (v NullableFlowpipeTriggerResponseMetadata) Get() *FlowpipeTriggerResponseMetadata {
	return v.value
}

func (v *NullableFlowpipeTriggerResponseMetadata) Set(val *FlowpipeTriggerResponseMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableFlowpipeTriggerResponseMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableFlowpipeTriggerResponseMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlowpipeTriggerResponseMetadata(val *FlowpipeTriggerResponseMetadata) *NullableFlowpipeTriggerResponseMetadata {
	return &NullableFlowpipeTriggerResponseMetadata{value: val, isSet: true}
}

func (v NullableFlowpipeTriggerResponseMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlowpipeTriggerResponseMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


