/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the ListProcessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProcessResponse{}

// ListProcessResponse struct for ListProcessResponse
type ListProcessResponse struct {
	Items []Process `json:"items,omitempty"`
	NextToken *string `json:"next_token,omitempty"`
}
func (o ListProcessResponse) GetResourceType() string {
	return "ListProcessResponse"
}
// NewListProcessResponse instantiates a new ListProcessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProcessResponse() *ListProcessResponse {
	this := ListProcessResponse{}
	return &this
}

// NewListProcessResponseWithDefaults instantiates a new ListProcessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProcessResponseWithDefaults() *ListProcessResponse {
	this := ListProcessResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListProcessResponse) GetItems() []Process {
	if o == nil || IsNil(o.Items) {
		var ret []Process
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProcessResponse) GetItemsOk() ([]Process, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListProcessResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Process and assigns it to the Items field.
func (o *ListProcessResponse) SetItems(v []Process) {
	o.Items = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListProcessResponse) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProcessResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListProcessResponse) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListProcessResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListProcessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProcessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextToken) {
		toSerialize["next_token"] = o.NextToken
	}
	return toSerialize, nil
}

type NullableListProcessResponse struct {
	value *ListProcessResponse
	isSet bool
}

func (v NullableListProcessResponse) Get() *ListProcessResponse {
	return v.value
}

func (v *NullableListProcessResponse) Set(val *ListProcessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListProcessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListProcessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProcessResponse(val *ListProcessResponse) *NullableListProcessResponse {
	return &NullableListProcessResponse{value: val, isSet: true}
}

func (v NullableListProcessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProcessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


