/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the ListVariableResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVariableResponse{}

// ListVariableResponse struct for ListVariableResponse
type ListVariableResponse struct {
	Items []Variable `json:"items,omitempty"`
	NextToken *string `json:"next_token,omitempty"`
}
func (o ListVariableResponse) GetResourceType() string {
	return "ListVariableResponse"
}
// NewListVariableResponse instantiates a new ListVariableResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVariableResponse() *ListVariableResponse {
	this := ListVariableResponse{}
	return &this
}

// NewListVariableResponseWithDefaults instantiates a new ListVariableResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVariableResponseWithDefaults() *ListVariableResponse {
	this := ListVariableResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListVariableResponse) GetItems() []Variable {
	if o == nil || IsNil(o.Items) {
		var ret []Variable
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVariableResponse) GetItemsOk() ([]Variable, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListVariableResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Variable and assigns it to the Items field.
func (o *ListVariableResponse) SetItems(v []Variable) {
	o.Items = v
}

// GetNextToken returns the NextToken field value if set, zero value otherwise.
func (o *ListVariableResponse) GetNextToken() string {
	if o == nil || IsNil(o.NextToken) {
		var ret string
		return ret
	}
	return *o.NextToken
}

// GetNextTokenOk returns a tuple with the NextToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVariableResponse) GetNextTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextToken) {
		return nil, false
	}
	return o.NextToken, true
}

// HasNextToken returns a boolean if a field has been set.
func (o *ListVariableResponse) HasNextToken() bool {
	if o != nil && !IsNil(o.NextToken) {
		return true
	}

	return false
}

// SetNextToken gets a reference to the given string and assigns it to the NextToken field.
func (o *ListVariableResponse) SetNextToken(v string) {
	o.NextToken = &v
}

func (o ListVariableResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVariableResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.NextToken) {
		toSerialize["next_token"] = o.NextToken
	}
	return toSerialize, nil
}

type NullableListVariableResponse struct {
	value *ListVariableResponse
	isSet bool
}

func (v NullableListVariableResponse) Get() *ListVariableResponse {
	return v.value
}

func (v *NullableListVariableResponse) Set(val *ListVariableResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListVariableResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListVariableResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVariableResponse(val *ListVariableResponse) *NullableListVariableResponse {
	return &NullableListVariableResponse{value: val, isSet: true}
}

func (v NullableListVariableResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVariableResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


