/*
Flowpipe

Flowpipe is workflow and pipelines for DevSecOps.

API version: 0.1.0
Contact: info@flowpipe.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package flowpipeapi

import (
	"encoding/json"
)

// checks if the FperrErrorDetailModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FperrErrorDetailModel{}

// FperrErrorDetailModel struct for FperrErrorDetailModel
type FperrErrorDetailModel struct {
	Location *string `json:"location,omitempty"`
	Message *string `json:"message,omitempty"`
}
func (o FperrErrorDetailModel) GetResourceType() string {
	return "FperrErrorDetailModel"
}
// NewFperrErrorDetailModel instantiates a new FperrErrorDetailModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFperrErrorDetailModel() *FperrErrorDetailModel {
	this := FperrErrorDetailModel{}
	return &this
}

// NewFperrErrorDetailModelWithDefaults instantiates a new FperrErrorDetailModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFperrErrorDetailModelWithDefaults() *FperrErrorDetailModel {
	this := FperrErrorDetailModel{}
	return &this
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *FperrErrorDetailModel) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FperrErrorDetailModel) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *FperrErrorDetailModel) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *FperrErrorDetailModel) SetLocation(v string) {
	o.Location = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *FperrErrorDetailModel) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FperrErrorDetailModel) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *FperrErrorDetailModel) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *FperrErrorDetailModel) SetMessage(v string) {
	o.Message = &v
}

func (o FperrErrorDetailModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FperrErrorDetailModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableFperrErrorDetailModel struct {
	value *FperrErrorDetailModel
	isSet bool
}

func (v NullableFperrErrorDetailModel) Get() *FperrErrorDetailModel {
	return v.value
}

func (v *NullableFperrErrorDetailModel) Set(val *FperrErrorDetailModel) {
	v.value = val
	v.isSet = true
}

func (v NullableFperrErrorDetailModel) IsSet() bool {
	return v.isSet
}

func (v *NullableFperrErrorDetailModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFperrErrorDetailModel(val *FperrErrorDetailModel) *NullableFperrErrorDetailModel {
	return &NullableFperrErrorDetailModel{value: val, isSet: true}
}

func (v NullableFperrErrorDetailModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFperrErrorDetailModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


